### ISSUE TITLE
update llvm15 to branch 24.08

### ISSUE THREAD

**Issue by baronleonardo** [flathub/org.freedesktop.Sdk.Extension.llvm15#14]
currently the last version we have is 24.08, and vscode now need 24.08

**Comment by Erick555** [comment]
llvm 15 is eol for a long time, please update to llvm 18

**Comment by baronleonardo** [comment]
ok, thanks

**Comment by orowith2os** [comment]
If you still needed llvm15, I just added a branch for it.

**Comment by baronleonardo** [comment]
good news thanks 😃

**Comment by Erick555** [comment]
Could you tell for which app you need it?

**Comment by baronleonardo** [comment]
I just was using clang 15 for development stuff nothing special, I just had to move forward and rebuild my projects
